### ISSUE TITLE
Websocket video. Possible garbage data

### ISSUE THREAD

**Issue by DenisRakhuba** [cycdpo/jsmpeg-player#13]
I'm trying to use this package for displaying video stream inside my angular app but receiving next error over and over again:
JSMpeg: Possible garbage data. Skipping.
No video in this case and issues counting stops only after I use destroy method. 
I've been using previously another jsmpeg package and there was no such problem. I guess there's built-in decoder for websocket videos. Anyway, its pretty old package and I was planning to switch to this one. Any suggestions how to handle my problem in Angular app?
Thanks

**Comment by cycjimmy** [comment]
I just wrote a [demo](https://github.com/cycjimmy/jsmpeg-ws-demo) that plays a video stream, but I didn't find the problem.

![screen shot 2019-03-01 at 11 08 55 am](https://user-images.githubusercontent.com/19383787/53613939-da3cb400-3c12-11e9-8ccc-5c18724b7217.png)


If possible, please provide your easy demo for troubleshooting. :simple_smile:

:heart: *In addition, you mentioned that jsmpeg is old and was planning to switch to this package. But this package is not an upgraded version of jsmpeg, just packaged jsmpeg, and all core codes are still jsmpeg.*

**Comment by DenisRakhuba** [comment]
Maybe the problem is with video format that is used on streams, that I'm trying to display? Here's the example url: 'ws://3.82.73.164:8090'
 Here's example of errors that I'm getting 
![screen shot 2019-03-01 at 9 57 13 am](https://user-images.githubusercontent.com/16452697/53624358-b3798000-3c08-11e9-8b47-b5a626d138bb.png)
As for package, I meant this one - [jsmpeg npm](https://www.npmjs.com/package/jsmpeg). It works fine on my side, but there's no destroy method in that version, and it's important for my app, since user may reopen many streams from time to time. 
Probably I need somehow to encode/decode streams, but not sure how to implement it on Angular, especially when I'm receiving urls to streams from an API requests.

**Comment by cycjimmy** [comment]
Check format for streaming first. JSMpeg only plays MPEG-TS containers. Maybe jsmpeg had supported other formats very early, but it is not supported now.

Related documents:
* [Encoding Video/Audio for JSMpeg](https://github.com/phoboslab/jsmpeg#encoding-videoaudio-for-jsmpeg)
* [Example Setup for Streaming: Raspberry Pi Live Webcam](https://github.com/phoboslab/jsmpeg#example-setup-for-streaming-raspberry-pi-live-webcam)

**Comment by DenisRakhuba** [comment]
Okay, thanks
